services:
    - type: web
      name: btm-bess-market-optimizer
      runtime: image
      plan: free
      region: singapore
      autoDeploy: true
      dockerfilePath: ./Dockerfile
      dockerContext: .
      image:
          url: ghcr.io/kayvanshah1/btm-bess-market-optimizer:latest
      healthCheckPath: /
      envVars:
          - key: BESS_PROJECT_ROOT
            value: /app
          - key: PORT
            value: "10000"
